name: documentation

on:
  push:
    branches: [devel]

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout submodules
        run: |
          git submodule update --init ndk/ofm
          git submodule update --init ndk/core
          git submodule update --init ndk/cards
      - name: Setup and build
        run: |
          sudo apt-get install python3-pip
          pip3 install sphinx==5.3.0 sphinx-vhdl sphinx_rtd_theme GitPython
          mkdir public
          mkdir public/html
          cp doc/source/index.html public/html/
          sphinx-build -M html doc/source public/devel
          git checkout main
          git submodule update
          sphinx-build -M html doc/source public/main
          mv public/main/html/ public/html/main
          mv public/devel/html/ public/html/devel
          touch public/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public/html
